/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AventonesRouteImport } from './routes/aventones'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as GoleoRouteImport } from './routes/goleo'
import { Route as TablaRouteImport } from './routes/tabla'
import { Route as PartidoIsoRouteImport } from './routes/partido.$iso'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AventonesRoute = AventonesRouteImport.update({
  id: '/aventones',
  path: '/aventones',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const GoleoRoute = GoleoRouteImport.update({
  id: '/goleo',
  path: '/goleo',
  getParentRoute: () => rootRouteImport,
} as any)
const TablaRoute = TablaRouteImport.update({
  id: '/tabla',
  path: '/tabla',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidoIsoRoute = PartidoIsoRouteImport.update({
  id: '/partido/$iso',
  path: '/partido/$iso',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aventones': typeof AventonesRoute
  '/calendario': typeof CalendarioRoute
  '/goleo': typeof GoleoRoute
  '/tabla': typeof TablaRoute
  '/partido/$iso': typeof PartidoIsoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aventones': typeof AventonesRoute
  '/calendario': typeof CalendarioRoute
  '/goleo': typeof GoleoRoute
  '/tabla': typeof TablaRoute
  '/partido/$iso': typeof PartidoIsoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aventones': typeof AventonesRoute
  '/calendario': typeof CalendarioRoute
  '/goleo': typeof GoleoRoute
  '/tabla': typeof TablaRoute
  '/partido/$iso': typeof PartidoIsoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/aventones' | '/calendario' | '/goleo' | '/tabla' | '/partido/$iso'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aventones' | '/calendario' | '/goleo' | '/tabla' | '/partido/$iso'
  id:
    | '__root__'
    | '/'
    | '/aventones'
    | '/calendario'
    | '/goleo'
    | '/tabla'
    | '/partido/$iso'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AventonesRoute: typeof AventonesRoute
  CalendarioRoute: typeof CalendarioRoute
  GoleoRoute: typeof GoleoRoute
  TablaRoute: typeof TablaRoute
  PartidoIsoRoute: typeof PartidoIsoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aventones': {
      id: '/aventones'
      path: '/aventones'
      fullPath: '/aventones'
      preLoaderRoute: typeof AventonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goleo': {
      id: '/goleo'
      path: '/goleo'
      fullPath: '/goleo'
      preLoaderRoute: typeof GoleoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabla': {
      id: '/tabla'
      path: '/tabla'
      fullPath: '/tabla'
      preLoaderRoute: typeof TablaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partido/$iso': {
      id: '/partido/$iso'
      path: '/partido/$iso'
      fullPath: '/partido/$iso'
      preLoaderRoute: typeof PartidoIsoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AventonesRoute: AventonesRoute,
  CalendarioRoute: CalendarioRoute,
  GoleoRoute: GoleoRoute,
  TablaRoute: TablaRoute,
  PartidoIsoRoute: PartidoIsoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
